### ISSUE TITLE
感觉更新后还没有之前好用了

### ISSUE THREAD

**Issue by yanrs17** [zerotrac/leetcode_problem_rating#10]
- 现在Keyword反而不能用ID搜索了，只能用Title。我之前一般就直接输入ID看Rating，Title就很长
- 现在没法按照ID排序了，以前点一下ID就能自动按照ID升序或者降序排序
- 现在还要专门按一下Query才能检索，之前直接就会自动出来检索的结果

**Comment by novice88** [comment]
您可以先试试这个 [link](https://kwliianopm.github.io/leetcode_problem_rating-1/#/)

1. Keyword支持ID（这个是我之前的遗漏）
2. 目前正考虑如何实现更好
3. 现在输入完按回车即可

**Comment by novice88** [comment]
> * 现在Keyword反而不能用ID搜索了，只能用Title。我之前一般就直接输入ID看Rating，Title就很长
> * 现在没法按照ID排序了，以前点一下ID就能自动按照ID升序或者降序排序
> * 现在还要专门按一下Query才能检索，之前直接就会自动出来检索的结果
> 
> 能不能把旧版本留着，需要的人选择自己用哪个版本？

已修复完成，先试试上面我贴的链接，代码得灵神同意再merge

**Comment by zerotrac** [comment]
感谢！我今天稍晚一些看一下代码，最近毕业季有一点点忙（

**Comment by zerotrac** [comment]
Seems the problems are solved. I will close this issue then.
