### ISSUE TITLE
有没有可能可以加上Tag然后可以用Tag Filter结果

### ISSUE THREAD

**Issue by yanrs17** [zerotrac/leetcode_problem_rating#12]
不知道抓取的时候能不能抓到Tag。我现在看这个的流程就是，先去力扣看某一个具体的Tag，然后把每一题都抄到Google Spreadsheet上，再去这里检索每一题的难度，再抄回到Spreadsheet，最后排序，按照排序的难度做题。对于就那么只有最多二三十个的题目的Tag，这样做还算容易，但如果有更多甚至上百个题目的Tag，就很难了，比如300多题的DP。如果太费劲就算了，谢谢！

**Comment by zerotrac** [comment]
根据你的描述，这完全可以你来写个脚本做这件事情，而与这个项目没啥关系？即：

- 写一个爬虫爬每个 tag 对应的题目编号
- 根据我开源的数据得到分数，然后写到 csv 里面

这件事情最好的解决方法是让力扣官方把竞赛积分加到他们的前端里面，而不是让一个独立的前端项目最后庞大成除了不需要题目描述以外和力扣本体一样。。。

**Comment by yanrs17** [comment]
谢谢大佬指点
