### ISSUE TITLE
Please restore visited style for hyperlinks

### ISSUE THREAD

**Issue by qszhu** [zerotrac/leetcode_problem_rating#14]
Previous one can quickly tell whether she has seen a problem before by checking the color of the hyperlink. This is no longer possible after the recent update. Please consider restoring the "visited" style of hyperlinks, otherwise one has to click through each link to be sure. Thanks.

**Comment by zerotrac** [comment]
The feature is a default setting for `<a href></a>` in html. The latest version uses Vue framework instead so it is not a default setting anymore. It is not what I designed "explicitly" in the previous version.

May I ask what is the purpose of showing "whether a problem is seen before or not"? A "clicked" link may indicate a seen problem, a try-to-solve but failed problem, a solved problem, or even a curious trial when finding this website at the first time. I have no idea why a "seen" problem is important, based on another fact that a browser history is easily cleaned.

**Comment by qszhu** [comment]
Well, since this is just a static site, it cannot display a check mark beside the problem like the main site do. A styled visited link is the closest alternative one can get. Styling visited links seems to be a [long-lost practice](https://www.nngroup.com/articles/change-the-color-of-visited-links/).

Any way, I found `ratings.txt` is all I need. You can close this issue if styling these links was never your intention.

**Comment by zerotrac** [comment]
Sure! As in #12, my proposal for this project is not something like a LeetCode or a mini-LeetCode website. Its target is to visualize the `ratings.txt` in a human-friendly format. The `ratings.txt` itself is also pretty well-formatted as an input file, so anyone can use the data to customize their own LeetCod-ing goals.

I will close this issue and start a new one to tell all the users that `rating.txt` is a good source to use, for everything in their mind.
