### ISSUE TITLE
Unable to access site

### ISSUE THREAD

**Issue by zakirhussainb** [zerotrac/leetcode_problem_rating#16]
@zerotrac 
On viewing the site, https://zerotrac.github.io/leetcode_problem_rating/#/ via github pages I am seeing the this error, `We're sorry but rating doesn't work properly without JavaScript enabled. Please enable it to continue.`
<img width="1673" alt="Screenshot 2022-08-03 at 4 18 45 PM" src="https://user-images.githubusercontent.com/28262681/182590736-730cf1f5-3e70-4e40-86ef-1b3920ef321b.png">

**Comment by zerotrac** [comment]
Let me check this. Seems to have this problem after the last data update.

**Comment by yanrs17** [comment]
I have the same issue

**Comment by novice88** [comment]
Due to the incompatible upgrade of vue-i18n, we should lock the version of vue-i18n

**Comment by zerotrac** [comment]
Thanks @novice88 !
I will start on working that by fixing the localization plugin version. It may take < 30min to finish.

Sorry for the late response. I am on my first week onboarding at work and hardly have time to deal with this issue.

**Comment by zerotrac** [comment]
It is okay now @zakirhussainb @yanrs17 
Please check and if looks good I will close this issue~

**Comment by zakirhussainb** [comment]
Thank you @zerotrac. The site is up now.
