### ISSUE TITLE
第293场周赛第四题rating很可能错误

### ISSUE THREAD

**Issue by shit-eater** [zerotrac/leetcode_problem_rating#17]
第293场周赛第四题，2276.统计区间中的整数数目，在rating网站上显示2222，这场周赛美国站参赛总量21677，这道题有1998人通过，明显不符合这个rating……

**Comment by zerotrac** [comment]
https://leetcode.com/discuss/general-discussion/2039695/Possible-mass-plagiarism-on-Leetcode-Weekly-Contest-293

这道题是因为那场比赛出现了大规模作弊行为。实际上并没有那么多人通过。
PS，我在计算 rating 的时候会把参加比赛次数 <5 的直接扔掉，那些作弊的基本都是第一次参加的小号（具体好像是哪个学校要求学生做那次周赛作为一次作业？），所以不会对真实的 rating 产生影响。

**Comment by zerotrac** [comment]
Close this issue because the reporter has not given responds for a long time.
