### ISSUE TITLE
能问下这个的分数和Codeforces的分数有什么关联吗

### ISSUE THREAD

**Issue by yanrs17** [zerotrac/leetcode_problem_rating#18]
想用这个分数来判断自己Codeforces（或者其他类似平台）应该要做哪个难度的题目，不知道大佬有什么总结出来什么换算的公式？也就是`CF = a * LC + b`裡面a和b的值，谢谢！

**Comment by zerotrac** [comment]
可以参考一下这个帖子：https://leetcode.cn/circle/discuss/nyEV47/

**Comment by yanrs17** [comment]
谢谢大佬！
