### ISSUE TITLE
Missing title slug for problem 1333

### ISSUE THREAD

**Issue by jakemcannon** [zerotrac/leetcode_problem_rating#19]
https://github.com/zerotrac/leetcode_problem_rating/blob/d33e2a562d57bdbbf012b22fc8f876c1f5040592/ratings.txt#L914

title slug:
filter-restaurants-by-vegan-friendly-price-and-distance

**Comment by zerotrac** [comment]
~~Investigating on that.~~

The reason is because there is a comma in the problem title, so the data is incorrectly split (the internal data uses comma as a delimiter).

I will try to use another delimiter instead. This fix may take a little bit longer.

**Comment by zerotrac** [comment]
@jakemcannon Solved. Thanks for pointing this out!

**Comment by jakemcannon** [comment]
No problem, I can grab all the slugs with no issue now, ty!
