### ISSUE TITLE
题目链接失效

### ISSUE THREAD

**Issue by qszhu** [zerotrac/leetcode_problem_rating#20]
以下题目的链接无法打开，似乎是由于题目的slug有过更新：

id: 1460
旧slug：make-two-arrays-equal-by-reversing-sub-arrays
新slug：make-two-arrays-equal-by-reversing-subarrays

id: 2086
旧slug: minimum-number-of-buckets-required-to-collect-rainwater-from-houses
新slug: minimum-number-of-food-buckets-to-feed-the-hamsters

**Comment by zerotrac** [comment]
好的，我来修改一下

**Comment by zerotrac** [comment]
@qszhu 应该是修改好啦

**Comment by qszhu** [comment]
Thanks!
