### ISSUE TITLE
A data request for my project

### ISSUE THREAD

**Issue by zqqcee** [zerotrac/leetcode_problem_rating#24]
Hello, zerotrac!
     thanks for this rating project!
     currently, I'm developing a chrome extension named "leetag",  and some function are as follow:
     1. Showing the tags of this problem
     2. Showing the hints of this problem
     3. Showing in which weekly contest this problem occurred (to be done)
     4. other information to be completed....

https://github.com/zerotrac/leetcode_problem_rating/assets/55946653/cdb6c42e-a52e-4648-89e0-ba3d769ca43a

For third function, I want to use the data from your website: https://zerotrac.github.io/leetcode_problem_rating/#/ . I wonder if there is any other way to get data without web crawlers on your website. Maybe some APIs exposed ? I gusse.
	
Looking forward to your reply！

**Comment by zerotrac** [comment]
You can use the `ratings.txt` file in this repository directly.

**Comment by zqqcee** [comment]
> You can use the `ratings.txt` file in this repository directly.

Thanks! I've finished the chrome extension leetag. The way to get data is fetching "https://zerotrac.github.io/leetcode_problem_rating/data.json".

This is the leetag: https://github.com/zqqcee/leetag
