### ISSUE TITLE
Wrong statistics

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [zerotrac/leetcode_problem_rating#25]
https://leetcode.cn/problems/number-of-times-binary-string-is-prefix-aligned/
目前力扣1375显示
![image](https://github.com/zerotrac/leetcode_problem_rating/assets/60914359/73fdb305-44ed-424f-ada3-73aa446d7cf6)
而网站显示
![image](https://github.com/zerotrac/leetcode_problem_rating/assets/60914359/d4d83e6b-7f9b-462f-9022-2c6cb78952d5)
数据可能有误。

**Comment by zerotrac** [comment]
估计又把题目的标题和 slug 改掉了，我来修一下

**Comment by zerotrac** [comment]
已修复
