### ISSUE TITLE
Missing statistics?

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [zerotrac/leetcode_problem_rating#26]
It seems that no.2235 - no.2238 cannot be found. I don't know why.

**Comment by zerotrac** [comment]
Let me take a look.
~Which weekly/biweekly contest are those problems belong to?~ It seems that they do not belong to any contests, do they?

**Comment by zerotrac** [comment]
It seems that they do not belong to any contests, do they?

**Comment by S-N-O-R-L-A-X** [comment]
> Let me take a look. ~Which weekly/biweekly contest are those problems belong to?~ It seems that they do not belong to any contests, do they?

I don't know. I have found them because they appeared in the leetcode daily.

**Comment by zerotrac** [comment]
Close this issue because they are not contest problems.
