### ISSUE TITLE
请问是自动ci的流程出错了吗?

### ISSUE THREAD

**Issue by ccagml** [zerotrac/leetcode_problem_rating#27]
https://github.com/zerotrac/leetcode_problem_rating/actions/runs/6449925888/job/17508770439
看起来像是github的action出错了
https://zerotrac.github.io/leetcode_problem_rating/data.json
这个数据好像不是最新的,和仓库的data.json不一样

**Comment by zerotrac** [comment]
对，那个 github CI 会卡在 `npm run build` 那一步，具体原因未知...

如果这周还是好不了的话我手动更新一下数据

**Comment by zerotrac** [comment]
Update: 我对前端本身不太了解，所以尝试了几个修复的方法，目前在 deploy 的时候会先将 node.js 升级到最新版本，然后在 `npm install` 的时候取消 `audit`。这样 CI 是可以通过的。

如果后续的几个星期问题不再出现的话，这个 issue 就可以关闭了。
