### ISSUE TITLE
第3024题名称和链接错误

### ISSUE THREAD

**Issue by raoyi** [zerotrac/leetcode_problem_rating#29]
3024题，名称应该是 三角形类型 ，链接地址也错了

**Comment by huxulm** [comment]
官方后面改了 题面 titleSlug 了, 这个仓库数据可能是增量更新导致以前错误数据没修正

**Comment by zerotrac** [comment]
已解决。竞赛相关的 graphql 返回结果仍然是「三角形类型 II」，只能手动更新。
