### ISSUE TITLE
Add localization for Chinese website and users

### ISSUE THREAD

**Issue by huxulm** [zerotrac/leetcode_problem_rating#5]
First of all, thank you very much for providing this website. I think it will be more friendly if you can add a Chinese version of the page.
（佬，未来能否增加一个 zh 的页面？❤️）

**Comment by zerotrac** [comment]
Which part of the webpage would you prefer to apply the Chinese localization?

**Comment by huxulm** [comment]
> Which part of the webpage would you prefer to apply the Chinese localization?

It would be great to have a page like: [https://zerotrac.github.io/zh/leetcode_problem_rating/](https://zerotrac.github.io/zh/leetcode_problem_rating/)
and it renders `data-zh.json` 

thanks!!💕

**Comment by zerotrac** [comment]
Sure. I will start working on that.
I am not skilled at frontend techs, so my plan is to:

- The current webpage: https://zerotrac.github.io/leetcode_problem_rating/ will show two links (en and zh) instead
- https://zerotrac.github.io/leetcode_problem_rating/en shows the English version
- https://zerotrac.github.io/leetcode_problem_rating/zh shows the Chinese version

**Comment by zerotrac** [comment]
@huxulm finished. I will close this issue.

**Comment by huxulm** [comment]
@zerotrac Great!!! More than one person will thank you!!
