### ISSUE TITLE
增加分数区间搜索的功能

### ISSUE THREAD

**Issue by novice88** [zerotrac/leetcode_problem_rating#8]
佬，我在leetcode上看到有扣友建议增加分数区间搜索的功能，但您说无法实现，我会写一点前端，这边我写了个demo,应该是能做到的，[传送门](https://kwliianopm.github.io/leetcode_problem_rating/#/)，但是并不是基于您的源码开发的。

**Comment by zerotrac** [comment]
啊我的意思是说我用的第三方那个 grid.js 库，它不支持区间搜索。我也不会用其它的框架啥的。
我看了下你使用 vue 做的？但我并不会这些。。。

**Comment by novice88** [comment]
> 

是的，我使用的Vue3+Element Plus,国际化相关的功能还没做，所以我在想是否能替换掉这个页面。

**Comment by zerotrac** [comment]
嗯，当然可以的！如果你有时间做好的话，我可以在这个 repo/网页端 里面加一个友链，或者直接 merge 覆盖这个 repo 都是可以的

**Comment by huxulm** [comment]
> 嗯，当然可以的！如果你有时间做好的话，我可以在这个 repo/网页端 里面加一个友链，或者直接 merge 覆盖这个 repo 都是可以的

@zerotrac 佬这个确实可以发展壮大一下。。。GOAL
